### ISSUE TITLE
confirm password problem

### ISSUE THREAD

**Issue by huijie717** [yiyingsong/TeamChallenge#5]
Confirming password does not working. Can someone help me to look at my code?

<label for="confirmPassword">Confirm Password</label> 
<input type="password" id="confirmPassword" name="confirmPassword" class="form-control" keyUp="compareTo()" ng-model="confirmPassword" ng-required/>

<p ng-if="password.length > 0 && confirmPassword.length > 0 && !compareTo()">Passwords do not match.</p>

**Comment by huijie717** [comment]
<label for="confirmPassword">Confirm Password</label> 
				<input type="password" id="confirmPassword" name="confirmPassword" class="form-control" keyUp="compareTo()" ng-model="confirmPassword" ng-required/>
				<p ng-if="password.length > 0 && confirmPassword.length > 0 && !compareTo()">Passwords do not match.</p>
				</br>

**Comment by huijie717** [comment]
<label for="confirmPassword">Confirm Password</label> 
				<input type="password" id="confirmPassword" name="confirmPassword" class="form-control" keyUp="compareTo()" ng-model="confirmPassword" ng-required/>
				<p ng-if="password.length > 0 && confirmPassword.length > 0 && !compareTo()">Passwords do not match.</p>
				</br>

**Comment by yiyingsong** [comment]
can you put the related code here so we can take a look?

**Comment by huijie717** [comment]
Here is my code.

`<label for="confirmPassword">Confirm Password</label> 
                <input type="password" id="confirmPassword" name="confirmPassword" class="form-control" keyUp="compareTo()" ng-model="confirmPassword" ng-required/>
                <p ng-if="password.length > 0 && confirmPassword.length > 0 && !compareTo()">Passwords do not match.</p>
                </br>`

**Comment by yiyingsong** [comment]
the code should be working   i didnt find any mistake 
make sure your compareTo method is working
maybe you should check in you did any typo in the js?

**Comment by huijie717** [comment]
Okay,sure.
Thanks a lot
